
FROM python:3.11

# Set Working Directory

WORKDIR /app

# Copy Project Files

COPY . .

# Install Dependencies

RUN pip install --no-cache-dir -r requirements.txt

# Expose Port

EXPOSE 8000

# Run FastAPI App

CMD [
    "uvicorn",
    "backend.app:app",
    "--host",
    "0.0.0.0",
    "--port",
    "8000"
]

